// Generated by CoffeeScript 1.4.0
(function() {

  this.dictionary = {
    title: 'Kanji Coverage',
    fonts: {
      gothic: ' (Sawarabi Gothic)',
      mincho: ' (Sawarabi Mincho)'
    },
    kyoikuKanji: 'Kyoiku Kanji',
    level1st: 'JIS 1st Level',
    level2nd: 'JIS 2nd Level',
    level3rd: 'JIS 3rd Level',
    level4th: 'JIS 4th Level'
  };

}).call(this);
