// Generated by CoffeeScript 1.4.0
(function() {

  this.dictionary = {
    title: '漢字収録率',
    fonts: {
      gothic: '（さわらびゴシック）',
      mincho: '（さわらび明朝）'
    },
    kyoikuKanji: '教育漢字',
    level1st: '第一水準漢字',
    level2nd: '第二水準漢字',
    level3rd: '第三水準漢字',
    level4th: '第四水準漢字'
  };

}).call(this);
