// Generated by CoffeeScript 1.4.0
(function() {
  var CurrentLangLabel, LangMenu, LangMenuItem, availableLanguages, main;

  availableLanguages = {
    en: "English",
    ja: "日本語"
  };

  main = function() {
    this.menu = new LangMenu();
    this.currentLabel = new CurrentLangLabel(this.menu);
    this.menu.buildItems(this.currentLabel.text());
    return this.currentLabel.$el.attr({
      "data-key": this.menu.currentLangSymbol
    });
  };

  CurrentLangLabel = (function() {

    function CurrentLangLabel(menu) {
      var _this = this;
      this.el = "#current-lang";
      this.$el = $(this.el);
      this.menu = menu;
      this.$el.click(function(event) {
        event.stopPropagation();
        return $(_this.menu.$el).css({
          "z-index": 99
        }).toggle();
      });
    }

    CurrentLangLabel.prototype.text = function() {
      return this.$el.text().replace(/\s/g, '');
    };

    return CurrentLangLabel;

  })();

  LangMenuItem = (function() {

    function LangMenuItem(langSymbol, langText) {
      this.$el = $(document.createElement("div"));
      this.$el.attr({
        "data-key": langSymbol,
        lang: langSymbol
      }).addClass("item").css({
        clear: "both"
      }).text(langText);
    }

    return LangMenuItem;

  })();

  LangMenu = (function() {

    function LangMenu() {
      this.el = "#lang-menu-container";
      this.$el = $(this.el);
    }

    LangMenu.prototype.buildItems = function(currentLangText) {
      var k, v,
        _this = this;
      for (k in availableLanguages) {
        v = availableLanguages[k];
        if (v === currentLangText) {
          this.currentLangSymbol = k;
        } else {
          this.$el.append(new LangMenuItem(k, v).$el);
        }
      }
      $('.item', this.$el).click(this.onclickItem);
      $('body').click(function() {
        return _this.$el.hide();
      });
    };

    LangMenu.prototype.onclickItem = function(event) {
      var key, root;
      console.log(this);
      if ($(this).attr("id") === "current-lang") {
        return;
      }
      key = $(this).attr("data-key") + '/';
      if (key === 'ja/') {
        key = '';
      }
      root = '../';
      if ($("div#current-lang").attr("data-key") === "ja") {
        root = './';
      }
      window.location = root + key;
    };

    return LangMenu;

  })();

  $(function() {
    return main();
  });

}).call(this);
