// Generated by CoffeeScript 1.4.0
(function() {
  var browserNameIs,
    __slice = [].slice;

  browserNameIs = function() {
    var deviceName;
    deviceName = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return deviceName.map(function(name) {
      if (navigator.userAgent.indexOf(name) > 0) {
        return 1;
      } else {
        return 9;
      }
    }).sort()[0] === 1;
  };

  if (browserNameIs('iPhone', 'iPod', 'Android')) {
    location.href = "/mobile" + location.pathname;
  }

}).call(this);
